"""Add DimensionAlias

Revision ID: 03a4c6b7124f
Revises: 69a68987fcc0
Create Date: 2026-08-01 15:55:14.064862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a4c6b7124f'
down_revision: Union[str, Sequence[str], None] = '69a68987fcc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dimension_id', sa.UUID(), nullable=False),
    sa.Column('alias_text', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension_id', 'alias_text', name='uq_dimension_alias')
    )
    op.create_index(op.f('ix_dimension_aliases_alias_text'), 'dimension_aliases', ['alias_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dimension_aliases_alias_text'), table_name='dimension_aliases')
    op.drop_table('dimension_aliases')
    # ### end Alembic commands ###
