"""Add CatalogSnapshot and IngestionRun updates

Revision ID: 0468c072526e
Revises: 790c9795d932
Create Date: 2026-08-01 16:22:37.833150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0468c072526e'
down_revision: Union[str, Sequence[str], None] = '790c9795d932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
