"""Fix DimensionAlias fields

Revision ID: 099dea7d031e
Revises: 03a4c6b7124f
Create Date: 2026-08-01 15:56:07.191121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099dea7d031e'
down_revision: Union[str, Sequence[str], None] = '03a4c6b7124f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimension_aliases', sa.Column('scope_type', sa.String(), nullable=False))
    op.add_column('dimension_aliases', sa.Column('scope_value', sa.String(), nullable=True))
    op.add_column('dimension_aliases', sa.Column('target_code', sa.String(), nullable=False))
    op.add_column('dimension_aliases', sa.Column('confidence', sa.String(), nullable=True))
    op.add_column('dimension_aliases', sa.Column('valid_from', sa.DateTime(), nullable=True))
    op.add_column('dimension_aliases', sa.Column('valid_to', sa.DateTime(), nullable=True))
    op.add_column('dimension_aliases', sa.Column('review_status', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_dimension_alias'), 'dimension_aliases', type_='unique')
    op.create_unique_constraint('uq_dimension_alias', 'dimension_aliases', ['scope_type', 'scope_value', 'alias_text', 'target_code'])
    op.drop_constraint(op.f('dimension_aliases_dimension_id_fkey'), 'dimension_aliases', type_='foreignkey')
    op.drop_column('dimension_aliases', 'dimension_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimension_aliases', sa.Column('dimension_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('dimension_aliases_dimension_id_fkey'), 'dimension_aliases', 'dimensions', ['dimension_id'], ['id'])
    op.drop_constraint('uq_dimension_alias', 'dimension_aliases', type_='unique')
    op.create_unique_constraint(op.f('uq_dimension_alias'), 'dimension_aliases', ['dimension_id', 'alias_text'], postgresql_nulls_not_distinct=False)
    op.drop_column('dimension_aliases', 'review_status')
    op.drop_column('dimension_aliases', 'valid_to')
    op.drop_column('dimension_aliases', 'valid_from')
    op.drop_column('dimension_aliases', 'confidence')
    op.drop_column('dimension_aliases', 'target_code')
    op.drop_column('dimension_aliases', 'scope_value')
    op.drop_column('dimension_aliases', 'scope_type')
    # ### end Alembic commands ###
