"""Add missing tables for ingestion

Revision ID: 541f526ba8b3
Revises: 0468c072526e
Create Date: 2026-08-01 16:34:16.433180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '541f526ba8b3'
down_revision: Union[str, Sequence[str], None] = '0468c072526e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_sha256', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_name', sa.String(), nullable=False),
    sa.Column('architecture', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=True),
    sa.Column('configuration_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('attempt_index', sa.Integer(), nullable=True),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('canonical_output', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'claim_id', 'attempt_index', name='uq_eval_pred')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('source_sha256', sa.String(), nullable=True),
    sa.Column('ingestion_type', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('items_discovered', sa.Integer(), nullable=True),
    sa.Column('items_created', sa.Integer(), nullable=True),
    sa.Column('items_updated', sa.Integer(), nullable=True),
    sa.Column('items_unchanged', sa.Integer(), nullable=True),
    sa.Column('items_failed', sa.Integer(), nullable=True),
    sa.Column('download_size_bytes', sa.Integer(), nullable=True),
    sa.Column('summary_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['catalog_snapshots.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_field_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('is_exact_match', sa.Boolean(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('error_category', sa.String(), nullable=True),
    sa.Column('expected_value', sa.JSON(), nullable=True),
    sa.Column('predicted_value', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['evaluation_predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fusion_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('selected_origin', sa.String(), nullable=False),
    sa.Column('decision_rule', sa.String(), nullable=False),
    sa.Column('baseline_value', sa.JSON(), nullable=True),
    sa.Column('llm_value', sa.JSON(), nullable=True),
    sa.Column('fusion_value', sa.JSON(), nullable=True),
    sa.Column('is_agreement', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['evaluation_predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('exception_type', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('truncated_response', sa.Text(), nullable=True),
    sa.Column('is_temporary', sa.Boolean(), nullable=True),
    sa.Column('resolution_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_hash', sa.String(), nullable=True),
    sa.Column('raw_file_path', sa.String(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('raw_hash', sa.String(), nullable=False),
    sa.Column('normalized_hash', sa.String(), nullable=True),
    sa.Column('business_hash', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('remote_published_at', sa.DateTime(), nullable=True),
    sa.Column('http_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_file_path', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('canonical_key', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('unit_multiplier', sa.Integer(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('base_period', sa.String(), nullable=True),
    sa.Column('first_period', sa.String(), nullable=True),
    sa.Column('last_period', sa.String(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('dimensions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'external_id', name='uq_series_external')
    )
    op.create_index(op.f('ix_series_external_id'), 'series', ['external_id'], unique=False)
    op.create_table('series_dimension_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('dimension_id', sa.UUID(), nullable=False),
    sa.Column('modality_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensions.id'], ),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'dimension_id', name='uq_series_dim')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_dimension_values')
    op.drop_index(op.f('ix_series_external_id'), table_name='series')
    op.drop_table('series')
    op.drop_table('resource_versions')
    op.drop_table('ingestion_items')
    op.drop_table('ingestion_errors')
    op.drop_table('fusion_decisions')
    op.drop_table('evaluation_field_scores')
    op.drop_table('ingestion_runs')
    op.drop_table('evaluation_predictions')
    op.drop_table('evaluation_metrics')
    op.drop_table('evaluation_runs')
    op.drop_table('catalog_snapshots')
    # ### end Alembic commands ###
