"""Add GoldAnnotation models

Revision ID: 55b3dc36c24b
Revises: 541f526ba8b3
Create Date: 2026-08-01 21:08:18.266662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b3dc36c24b'
down_revision: Union[str, Sequence[str], None] = '541f526ba8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('dataflow_id', sa.String(), nullable=False),
    sa.Column('metadata_snapshot_id', sa.String(), nullable=False),
    sa.Column('expected_status', sa.String(), nullable=False),
    sa.Column('codes_by_dimension', sa.JSON(), nullable=True),
    sa.Column('time_window', sa.JSON(), nullable=True),
    sa.Column('allowed_defaults', sa.JSON(), nullable=True),
    sa.Column('forbidden_substitutions', sa.JSON(), nullable=True),
    sa.Column('ambiguities', sa.String(), nullable=True),
    sa.Column('limitations', sa.String(), nullable=True),
    sa.Column('annotation_provenance', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'dataflow_id', 'metadata_snapshot_id', name='uq_gold_annotation')
    )
    op.create_table('gold_annotation_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('annotation_id', sa.UUID(), nullable=False),
    sa.Column('expected_ordered_key', sa.String(), nullable=False),
    sa.Column('relevance', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['gold_annotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gold_annotation_keys')
    op.drop_table('gold_annotations')
    # ### end Alembic commands ###
