"""Initial schema and Lot 8 Step 1

Revision ID: 69a68987fcc0
Revises: 
Create Date: 2026-08-01 15:54:40.438271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69a68987fcc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stable_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True),
    sa.Column('annotation_status', sa.String(), nullable=True),
    sa.Column('corpus_version', sa.String(), nullable=True),
    sa.Column('paraphrase_group_id', sa.String(), nullable=True),
    sa.Column('event_group_id', sa.String(), nullable=True),
    sa.Column('split_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_event_group_id'), 'claims', ['event_group_id'], unique=False)
    op.create_index(op.f('ix_claims_paraphrase_group_id'), 'claims', ['paraphrase_group_id'], unique=False)
    op.create_index(op.f('ix_claims_stable_id'), 'claims', ['stable_id'], unique=True)
    op.create_table('dataflow_dimensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('dataflow_id', sa.String(), nullable=False),
    sa.Column('dimension_id', sa.String(), nullable=False),
    sa.Column('canonical_concept', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('representation_type', sa.String(), nullable=True),
    sa.Column('codelist', sa.String(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('metadata_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'dataflow_id', 'dimension_id', name='uq_dataflow_dimension')
    )
    op.create_index(op.f('ix_dataflow_dimensions_dataflow_id'), 'dataflow_dimensions', ['dataflow_id'], unique=False)
    op.create_index(op.f('ix_dataflow_dimensions_snapshot_id'), 'dataflow_dimensions', ['snapshot_id'], unique=False)
    op.create_index('uq_dataflow_dim_position', 'dataflow_dimensions', ['snapshot_id', 'dataflow_id', 'position'], unique=True, postgresql_where=sa.text("role = 'SERIES'"))
    op.create_table('dataflow_modalities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('dataflow_id', sa.String(), nullable=False),
    sa.Column('dimension_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('original_label', sa.String(), nullable=False),
    sa.Column('normalized_label', sa.String(), nullable=True),
    sa.Column('parent_code', sa.String(), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'dataflow_id', 'dimension_id', 'code', name='uq_dataflow_modality')
    )
    op.create_index(op.f('ix_dataflow_modalities_dataflow_id'), 'dataflow_modalities', ['dataflow_id'], unique=False)
    op.create_index(op.f('ix_dataflow_modalities_dimension_id'), 'dataflow_modalities', ['dimension_id'], unique=False)
    op.create_index(op.f('ix_dataflow_modalities_snapshot_id'), 'dataflow_modalities', ['snapshot_id'], unique=False)
    op.create_table('dimensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('label_fr', sa.String(), nullable=True),
    sa.Column('label_en', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('semantic_role', sa.String(), nullable=True),
    sa.Column('logical_type', sa.String(), nullable=True),
    sa.Column('is_temporal', sa.Boolean(), nullable=True),
    sa.Column('is_geographical', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimensions_external_id'), 'dimensions', ['external_id'], unique=True)
    op.create_table('parser_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=True),
    sa.Column('parser_type', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('temperature', sa.String(), nullable=True),
    sa.Column('json_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_date', sa.DateTime(), nullable=True),
    sa.Column('evaluated_corpus', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieval_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('index_version', sa.String(), nullable=True),
    sa.Column('lexical_config', sa.String(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('fusion_method', sa.String(), nullable=True),
    sa.Column('reranker_model', sa.String(), nullable=True),
    sa.Column('k_value', sa.Integer(), nullable=True),
    sa.Column('evaluated_corpus', sa.String(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('main_format', sa.String(), nullable=True),
    sa.Column('protocol_version', sa.String(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_code'), 'sources', ['code'], unique=True)
    op.create_table('claim_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('annotator_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('overall_confidence', sa.String(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('validator_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_parse_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('structured_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_schema_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['parser_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_semantics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('normalized_indicator', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('start_period', sa.String(), nullable=True),
    sa.Column('end_period', sa.String(), nullable=True),
    sa.Column('time_granularity', sa.String(), nullable=True),
    sa.Column('territory', sa.String(), nullable=True),
    sa.Column('population', sa.String(), nullable=True),
    sa.Column('comparison_base', sa.String(), nullable=True),
    sa.Column('seasonal_adjustment', sa.String(), nullable=True),
    sa.Column('answerability_status', sa.String(), nullable=True),
    sa.Column('full_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('external_type', sa.String(), nullable=True),
    sa.Column('title_fr', sa.String(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('subtheme', sa.String(), nullable=True),
    sa.Column('producer', sa.String(), nullable=True),
    sa.Column('geo_coverage', sa.String(), nullable=True),
    sa.Column('main_frequency', sa.String(), nullable=True),
    sa.Column('main_unit', sa.String(), nullable=True),
    sa.Column('doc_url', sa.String(), nullable=True),
    sa.Column('data_url', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_remote_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_type', 'external_id', name='uq_dataset_external')
    )
    op.create_index(op.f('ix_datasets_external_id'), 'datasets', ['external_id'], unique=False)
    op.create_table('modalities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dimension_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label_fr', sa.String(), nullable=True),
    sa.Column('label_en', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_code', sa.String(), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension_id', 'code', name='uq_modality_code')
    )
    op.create_index(op.f('ix_modalities_code'), 'modalities', ['code'], unique=False)
    op.create_table('resolution_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parser_run_id', sa.UUID(), nullable=True),
    sa.Column('retrieval_run_id', sa.UUID(), nullable=True),
    sa.Column('nomenclature_version', sa.String(), nullable=True),
    sa.Column('rules_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ambiguities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('automatic_decisions', sa.Integer(), nullable=True),
    sa.Column('human_decisions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parser_run_id'], ['parser_runs.id'], ),
    sa.ForeignKeyConstraint(['retrieval_run_id'], ['retrieval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_type', sa.String(), nullable=False),
    sa.Column('url_template', sa.String(), nullable=False),
    sa.Column('expected_format', sa.String(), nullable=True),
    sa.Column('http_method', sa.String(), nullable=True),
    sa.Column('supported_parameters', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_dataset_judgments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_dimension_judgments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('dimension_id', sa.UUID(), nullable=True),
    sa.Column('expected_modality_id', sa.UUID(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('acceptable_alternative_id', sa.UUID(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('real_ambiguity', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['acceptable_alternative_id'], ['modalities.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensions.id'], ),
    sa.ForeignKeyConstraint(['expected_modality_id'], ['modalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_query_gold',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('expected_transformation', sa.String(), nullable=True),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answerability_verdict', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('annotation_id', sa.UUID(), nullable=True),
    sa.Column('start_pos', sa.Integer(), nullable=True),
    sa.Column('end_pos', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['annotation_id'], ['claim_annotations.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('alias_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_dimensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('dimension_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('external_codelist', sa.String(), nullable=True),
    sa.Column('modality_count', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'dimension_id', name='uq_dataset_dimension'),
    sa.UniqueConstraint('dataset_id', 'position', name='uq_dataset_dimension_position')
    )
    op.create_table('dataset_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=False),
    sa.Column('target_dataset_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.String(), nullable=True),
    sa.Column('detection_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['target_dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieval_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('lexical_rank', sa.Integer(), nullable=True),
    sa.Column('vector_rank', sa.Integer(), nullable=True),
    sa.Column('fusion_rank', sa.Integer(), nullable=True),
    sa.Column('rerank_rank', sa.Integer(), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['retrieval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_dimension_modalities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_dimension_id', sa.UUID(), nullable=False),
    sa.Column('modality_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_dimension_id'], ['dataset_dimensions.id'], ),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_dimension_id', 'modality_id', name='uq_dataset_dim_modality')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_dimension_modalities')
    op.drop_table('retrieval_results')
    op.drop_table('dataset_relations')
    op.drop_table('dataset_dimensions')
    op.drop_table('dataset_aliases')
    op.drop_table('claim_spans')
    op.drop_table('claim_query_gold')
    op.drop_table('claim_dimension_judgments')
    op.drop_table('claim_dataset_judgments')
    op.drop_table('source_endpoints')
    op.drop_table('resolution_runs')
    op.drop_index(op.f('ix_modalities_code'), table_name='modalities')
    op.drop_table('modalities')
    op.drop_index(op.f('ix_datasets_external_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_table('claim_semantics')
    op.drop_table('claim_parse_predictions')
    op.drop_table('claim_annotations')
    op.drop_index(op.f('ix_sources_code'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('retrieval_runs')
    op.drop_table('parser_runs')
    op.drop_index(op.f('ix_dimensions_external_id'), table_name='dimensions')
    op.drop_table('dimensions')
    op.drop_index(op.f('ix_dataflow_modalities_snapshot_id'), table_name='dataflow_modalities')
    op.drop_index(op.f('ix_dataflow_modalities_dimension_id'), table_name='dataflow_modalities')
    op.drop_index(op.f('ix_dataflow_modalities_dataflow_id'), table_name='dataflow_modalities')
    op.drop_table('dataflow_modalities')
    op.drop_index('uq_dataflow_dim_position', table_name='dataflow_dimensions', postgresql_where=sa.text("role = 'SERIES'"))
    op.drop_index(op.f('ix_dataflow_dimensions_snapshot_id'), table_name='dataflow_dimensions')
    op.drop_index(op.f('ix_dataflow_dimensions_dataflow_id'), table_name='dataflow_dimensions')
    op.drop_table('dataflow_dimensions')
    op.drop_index(op.f('ix_claims_stable_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_paraphrase_group_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_event_group_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
