"""Update ResolutionRun and add ResolutionCandidate

Revision ID: 790c9795d932
Revises: 9393901bc0f6
Create Date: 2026-08-01 16:00:27.229318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '790c9795d932'
down_revision: Union[str, Sequence[str], None] = '9393901bc0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolution_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resolution_run_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('candidate_key', sa.String(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('method_used', sa.String(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['resolution_run_id'], ['resolution_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('resolution_runs', sa.Column('parser_version', sa.String(), nullable=True))
    op.add_column('resolution_runs', sa.Column('catalog_version', sa.String(), nullable=True))
    op.add_column('resolution_runs', sa.Column('alias_version', sa.String(), nullable=True))
    op.add_column('resolution_runs', sa.Column('rules_version', sa.String(), nullable=True))
    op.add_column('resolution_runs', sa.Column('strategy', sa.String(), nullable=True))
    op.add_column('resolution_runs', sa.Column('config_hash', sa.String(), nullable=True))
    op.add_column('resolution_runs', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.drop_column('resolution_runs', 'human_decisions')
    op.drop_column('resolution_runs', 'rules_applied')
    op.drop_column('resolution_runs', 'nomenclature_version')
    op.drop_column('resolution_runs', 'ambiguities')
    op.drop_column('resolution_runs', 'results')
    op.drop_column('resolution_runs', 'automatic_decisions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resolution_runs', sa.Column('automatic_decisions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resolution_runs', sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('resolution_runs', sa.Column('ambiguities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('resolution_runs', sa.Column('nomenclature_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resolution_runs', sa.Column('rules_applied', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('resolution_runs', sa.Column('human_decisions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('resolution_runs', 'latency_ms')
    op.drop_column('resolution_runs', 'config_hash')
    op.drop_column('resolution_runs', 'strategy')
    op.drop_column('resolution_runs', 'rules_version')
    op.drop_column('resolution_runs', 'alias_version')
    op.drop_column('resolution_runs', 'catalog_version')
    op.drop_column('resolution_runs', 'parser_version')
    op.drop_table('resolution_candidates')
    # ### end Alembic commands ###
