"""Add AvailableSeriesKey

Revision ID: 9393901bc0f6
Revises: dfd94d3bee4b
Create Date: 2026-08-01 15:59:37.768809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9393901bc0f6'
down_revision: Union[str, Sequence[str], None] = 'dfd94d3bee4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_series_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('dataflow_id', sa.String(), nullable=False),
    sa.Column('ordered_key', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('dimensions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idbank', sa.String(), nullable=True),
    sa.Column('first_period', sa.String(), nullable=True),
    sa.Column('last_period', sa.String(), nullable=True),
    sa.Column('availability_source', sa.String(), nullable=True),
    sa.Column('observation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'dataflow_id', 'ordered_key', name='uq_available_series_key')
    )
    op.create_index(op.f('ix_available_series_keys_dataflow_id'), 'available_series_keys', ['dataflow_id'], unique=False)
    op.create_index(op.f('ix_available_series_keys_idbank'), 'available_series_keys', ['idbank'], unique=False)
    op.create_index(op.f('ix_available_series_keys_key_hash'), 'available_series_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_available_series_keys_snapshot_id'), 'available_series_keys', ['snapshot_id'], unique=False)
    op.create_index('ix_series_dimensions_gin', 'available_series_keys', ['dimensions_json'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_series_dimensions_gin', table_name='available_series_keys', postgresql_using='gin')
    op.drop_index(op.f('ix_available_series_keys_snapshot_id'), table_name='available_series_keys')
    op.drop_index(op.f('ix_available_series_keys_key_hash'), table_name='available_series_keys')
    op.drop_index(op.f('ix_available_series_keys_idbank'), table_name='available_series_keys')
    op.drop_index(op.f('ix_available_series_keys_dataflow_id'), table_name='available_series_keys')
    op.drop_table('available_series_keys')
    # ### end Alembic commands ###
