"""Add DimensionDefaultPolicy

Revision ID: dfd94d3bee4b
Revises: 099dea7d031e
Create Date: 2026-08-01 15:58:27.969189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd94d3bee4b'
down_revision: Union[str, Sequence[str], None] = '099dea7d031e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension_default_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('dataflow_id', sa.String(), nullable=False),
    sa.Column('dimension_id', sa.String(), nullable=False),
    sa.Column('policy_type', sa.String(), nullable=False),
    sa.Column('target_modality_code', sa.String(), nullable=True),
    sa.Column('justification', sa.String(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'dataflow_id', 'dimension_id', name='uq_dimension_policy')
    )
    op.create_index(op.f('ix_dimension_default_policies_dataflow_id'), 'dimension_default_policies', ['dataflow_id'], unique=False)
    op.create_index(op.f('ix_dimension_default_policies_dimension_id'), 'dimension_default_policies', ['dimension_id'], unique=False)
    op.create_index(op.f('ix_dimension_default_policies_snapshot_id'), 'dimension_default_policies', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dimension_default_policies_snapshot_id'), table_name='dimension_default_policies')
    op.drop_index(op.f('ix_dimension_default_policies_dimension_id'), table_name='dimension_default_policies')
    op.drop_index(op.f('ix_dimension_default_policies_dataflow_id'), table_name='dimension_default_policies')
    op.drop_table('dimension_default_policies')
    # ### end Alembic commands ###
